#version: 2.1
#
#orbs:
#  python: circleci/python@1.5.0
#
#jobs:
#  build-and-test:
#    docker:
#      - image: cimg/python:3.10.2
#    steps:
#      - checkout
#      - run:
#          name: Install dependencies
#          command: pip install pytest
#      - run:
#          name: Run tests
#          command: pytest main.py
#
#workflows:
#  sample:
#    jobs:
#      - build-and-test

version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - store_test_results:
          path: result.xml
workflows:
  main:
    jobs:
#      - python/test:
#          args: '-v --junitxml="result.xml"'
#          pkg-manager: pipenv
#          test-tool: pytest
      - run:
          name: "install pytest"
          command: |
            pip install pytest
            pytest main.py -v --junitxml="result.xml"
      - publish